name: quran_app
description: Quran app
version: 1.0.1+3
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.3.8

dependencies:
  bloc: ^8.1.0
  date_picker_timeline: ^1.2.3
  dio: ^4.0.6
  dio_cache_interceptor: ^3.3.1
  dio_cache_interceptor_hive_store: ^3.2.0
  equatable: ^2.0.5
  feedback: ^2.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_email_sender: ^5.2.0
  flutter_local_notifications: ^13.0.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.14
  flutter_native_splash: ^2.2.18
  flutter_screenutil: ^5.6.0
  flutter_slidable: ^3.0.0
  flutter_svg: ^1.1.6
  flutter_timezone: ^1.0.8
  freezed_annotation: ^2.4.1
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  just_audio: ^0.9.31
  notification_permissions: ^0.6.1
  path_provider: ^2.0.12
  scrollable_positioned_list: ^0.3.5
  shared_preferences: ^2.0.15

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  hive_generator: ^2.0.0
  json_serializable: ^6.7.1
  mocktail: ^0.3.0
  very_good_analysis: ^5.1.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon/launcher.png"
  min_sdk_android: 20
  adaptive_icon_background: "#234D60"
  adaptive_icon_foreground: "assets/launcher_icon/icon_adaptive.png"

flutter_native_splash:
  color: "#244C64"
  image: assets/launcher_icon/launcher.png

  android_12:
    image: assets/launcher_icon/launcher.png
    icon_background_color: "#244C64"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/sources/
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: IsepMisbah
      fonts:
        - asset: assets/fonts/isepMisbah.ttf
    - family: DsDigital
      fonts:
        - asset: assets/fonts/dsdigi.ttf
